### ISSUE TITLE
과제 1번 질문입니다

### ISSUE THREAD

**Issue by waterbooom** [kangjeonghwan/CB33988-059#1]
안녕하세요 웹응용프로그래밍 059분반 202055517 김범수입니다
과제1번을 하는데에 있어서 테이블 안에 버튼을 추가하는데에 있어서 버튼을 제일 밑쪽으로 내리기위하여
tr,td를 사용하려고하는데 과제1번에는 td라고 묶여있지 않아서 쓰면 안되는지 궁금하여 여쭈어봅니다.

**Comment by kangjeonghwan** [comment]
안녕하세요.
과제 담당조교 강정환입니다.

해당 버튼 부분을 구현하는 방법에 대해서는 감점 요인이 없습니다.
따라서 tr, td를 사용하셔도 문제 없습니다.

감사합니다.
