### ISSUE TITLE
과제 4번 질문입니다.

### ISSUE THREAD

**Issue by canyos** [kangjeonghwan/CB33988-059#3]
안녕하십니까 웹응용프로그래밍 59분반 201924548 이풍헌입니다.

1. Goal2에서  outputCartRow함수는 파라미터가 있는데  조교님께서  한번에  두 개의 행을 전부 그리라고 설명하셔서
 하나의 행을 출력하는 함수를  반복문으로 호출하는 것인지 아니면 함수는 한번만 호출하고 함수에서 두 개의 행을 모두 그려야 하는 것인지 궁금합니다.

2. chapter08-project2.html을 php파일로 바꾼 후 작성 후에 html로 바꿔서 기존파일과 같이 압축해서 제출하면 되는지 아니면 그대로 php파일로 제출해야 하는지 궁금합니다.

감사합니다

**Comment by kangjeonghwan** [comment]
안녕하세요.
조교 강정환입니다.

1. Goal2에서 outputCartRow함수는 파라미터가 있는데 조교님께서 한번에 두 개의 행을 전부 그리라고 설명하셔서
하나의 행을 출력하는 함수를 반복문으로 호출하는 것인지 아니면 함수는 한번만 호출하고 함수에서 두 개의 행을 모두 그려야 하는 것인지 궁금합니다.

>> 함수를 반복문으로 호출해도 크게 문제는 없을 것 같습니다. 또는 함수를 두 번 호출하시되 그때의 파라미터만 잘 맞추어주셔도 됩니다. 해당 함수를 통해 정형화된 행 출력이 가능하기만 하면 됩니다.

2. chapter08-project2.html을 php파일로 바꾼 후 작성 후에 html로 바꿔서 기존파일과 같이 압축해서 제출하면 되는지 아니면 그대로 php파일로 제출해야 하는지 궁금합니다.

>> php 파일로 유지한 채로 제출해주세요.

감사합니다.
