### ISSUE TITLE
과제 4번 css 형식 질문입니다.

### ISSUE THREAD

**Issue by jbi7336** [kangjeonghwan/CB33988-059#4]
안녕하세요 201724553 장대익입니다.

이번 과제 수행을 하면서 class moveRight css 형식이 주어진 pdf에서 보여지는 형식과 다르게 보여
임의로 text-align을 수정하여 제출하려 하는데 css 파일은 따로 건드리면 안되는건지,
예시와 다른 css 형식을 가지고 있어도 그대로 제출을 하면되는지 궁금합니다.

**Comment by kangjeonghwan** [comment]
안녕하세요.
조교 강정환입니다.

과제의 goals를 달성하거나, 지시사항대로 구현하기 위해서 다른 파일을 수정하는 것은 금지됩니다.

하지만 text-align과 같이 과제의 goal과 직접적인 연관이 없는 경우, css 파일을 수정하셔도 무관합니다.
