### ISSUE TITLE
과제 5번 질문입니다.

### ISSUE THREAD

**Issue by jbi7336** [kangjeonghwan/CB33988-059#5]
안녕하세요. 201724553 장대익입니다.

이번 과제를 진행하면서 주어진 스켈레톤 코드의 function runQuery($pdo, $sql, $parameters=array()) 부분에서 파라미터에 대한
배열타입 검사를 진행한 뒤 쿼리를 동작하라 라고 주석으로 설명이 되어있습니다.

그런데, 여기서 $parameters 라는 변수가 존재하는 의미(?) 라고 해야 할까요? 조교님 께서 생각하신 $parameters 변수의 사용처가 너무 궁금합니다. 저의 짧은 php 지식으로는 $parameters 변수가 필요하다는 생각이 들지 않아서, 어떠한 방향성을 가지고 주석대로 코드를 진행하고 처리해야 할지 감이 안 잡혀 질문남깁니다.

**Comment by kangjeonghwan** [comment]
안녕하세요.

readSelectCustomers($lastname) 함수의 경우,
runQuery 함수를 실행할 때 $lastname 매개변수를 통한 array를 runQuery 함수의 파라미터로 넘겨줘야 합니다.
readSelectCustomers($lastname) 함수를 제외한 나머지 3개의 함수는 해당 파라미터를 null 값으로 넘겨줘도 문제가 없습니다.

$parameters 변수는 readSelectCustomers($lastname) 함수의 runQuery 호출을 위해 필요하다고 생각하시고 구현하시면 됩니다.
