### ISSUE TITLE
7번 과제 질문입니다.

### ISSUE THREAD

**Issue by jbi7336** [kangjeonghwan/CB33988-059#6]
201724553 장대익입니다.

과제를 진행하면서 주어진 3개의 함수 내부에서 반복적으로 사용되거나, 공통되는 특징을 가지는 기능을 외부 함수로 빼내어
코드를 작성해도 될까요?

**Comment by kangjeonghwan** [comment]
안녕하세요. 조교 강정환입니다.

새로운 함수를 정의하고 구현하시되,
이를 동일한 js 파일 내에서 수행하신다면 문제 없습니다.
